*** Settings ***
Library    RequestsLibrary  
Library    JsonLibrary    
Library    String    
# Library    GenerateOidcToken
Library    BaselineComparator    

# Library    Collections   
# Library    OperatingSystem 
Variables    ../../ConfigFile/GlobalConfig.py
Resource    ../../ConfigFile/ImportFile.robot



Suite Teardown    Delete All Sessions

Test Setup    GIVEN VALID AUTHENTICATION TOKEN AND SESSION IS CREATED

*** Variables ***
@{IGNORED_KEYS_JSON_COMPARE}    Create List    comment    legalDisclaimer    lastUpdatedFromSource    

${HEADERS}
${RESPONSE}
${API_REQUEST_FROM_FILE}



*** Test Cases ***

GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_001_WHEN END DATE IS FEB29 & DATE RANGE IS 2DAYS WITH LOOKBACK AND LOCKOUT
    [Documentation]    This test case has lookback and lockout applied and tested for SOFR with endDate as 29thFeb
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_001.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_001.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_001.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_001.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_001.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_004_WHEN END DATE IS HOLIDAY WITH LOOKBACK AND LOCKOUT AND DAYCOUNTCONVENTION=ACT/365
    [Documentation]    This test case has lookback,lockout applied , dayCountConvention is ACT/365 for SOFR 
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_004.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_004.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_004.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_004.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_004.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_007_WHEN DATES ARE BUSINESS DAYS WITH LOOKBACK AND LOCKOUT
    [Documentation]    This test case has lookback,lockout applied , both startDate and endDate are business days
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_007.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_007.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_007.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_007.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_007.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_009_WHEN START DATE IS MONTH END & END DATE IS WEEKEND WITH LOOKBACK AND LOCKOUT
    [Documentation]    This test case has lookback >lockout applied , startDate falls on Month end and endDate is a weekend
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_009.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_009.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_009.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_009.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_009.txt    ${IGNORED_KEYS_JSON_COMPARE}
    
GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_016_WHEN BOTH DATES FALLS ON WEEEKEND WITH LOOKBACK AND LOCKOUT AND SHOWDAILYDETAILS IS FALSE
    [Documentation]    This test case has lookback >lockout applied , Both dates are weekend and showDailyDetails=false
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_016.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_016.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_016.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_016.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_016.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_017_WHEN START DATES IS FRIDAY AND END DATE FALLS ON WEEEKEND WITH LOOKBACK AND LOCKOUT
    [Documentation]    This test case has lookback >lockout applied , startDate is Friday and endDate is Feb29th.
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_017.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_017.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_017.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_017.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_017.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_018_ WHEN START DATE IS A WEEKEND AND END DATE IS BUSINESS DAY WITH LOOKBACK AND LOCKOUT
    [Documentation]    This test case has lookback < lockout applied , startDate is a weekend and endDate falls on business day.
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_018.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_018.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_018.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_018.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_018.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_023_ WHEN START DATE (START OF YEAR) AND END DATE ARE WEEKENDS WITH LOOKBACK AND LOCKOUT
    [Documentation]    This test case has lookback > lockout applied , startDate is start of the year date falling on weekend and endDate also a weekend.
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_023.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_023.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_023.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_023.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_023.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_024_ WHEN OPS IS APPLICABLE AND START DATE IS MONDAY AND END DATE IS FRIDAY
    [Documentation]    This test case has startDate = Monday and endDate =Friday (Month-end) and OPS is enabled
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_024.json
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_024.json
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_024.json   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_024.json   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_024.json    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_025_ WHEN START DATES IS MONDAY AND END DATE FALLS ON WEEEKEND WITH LOOKBACK AND LOCKOUT
    [Documentation]    This test case has lookback < lockout applied , startDate is Monday and endDate is Saturday.
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_025.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_025.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_025.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_025.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_025.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_031_WHEN OPS IS APPLICABLE, START DATE IS FRIDAY AND END DATE IS TUESDAY
    [Documentation]    This test case has startDate = Friday and endDate =Tuesday and OPS is enabled
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_031.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_031.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_031.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_031.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_031.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRCSOFRCA_034_WHEN OPS IS APPLICABLE, START DATE IS FRIDAY AND END DATE IS END_OF_YEAR
    [Documentation]    This test case has startDate = Friday and endDate =Tuesday (end of Year) and OPS is enabled and showDailyDetails=False
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SOFR\\Request_ARRCSOFRCA_034.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_034.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_034.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SOFR\\Response_ARRCSOFRCA_034.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SOFR\\Response_ARRCSOFRCA_034.txt    ${IGNORED_KEYS_JSON_COMPARE}
