*** Settings ***
Library    RequestsLibrary  
Library    JsonLibrary    
Library    String    
# Library    GenerateOidcToken
Library    BaselineComparator    

# Library    Collections   
# Library    OperatingSystem 
Variables    ../../ConfigFile/GlobalConfig.py
Resource    ../../ConfigFile/ImportFile.robot



Suite Teardown    Delete All Sessions

Test Setup    GIVEN VALID AUTHENTICATION TOKEN AND SESSION IS CREATED

*** Variables ***
@{IGNORED_KEYS_JSON_COMPARE}    Create List    comment    legalDisclaimer    lastUpdatedFromSource    

${HEADERS}
${RESPONSE}
${API_REQUEST_FROM_FILE}



*** Test Cases ***


GET_VALIDATE RATE_FOR_TC_ARRSONIACA_005_WHEN START DATE AND END DATE FALLS ON HOLIDAY WITH LOOKBACK AND LOCKOUT
    [Documentation]    This test case has lookback < lockout applied and tested for SONIA with startDate and endDate as Holidays.
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_005.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_005.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_005.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_005.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_005.txt    ${IGNORED_KEYS_JSON_COMPARE}


GET_VALIDATE RATE_FOR_TC_ARRSONIACA_006_WHEN START DATE AND END DATE FALLS ON BUSINESS DAYS WITH OPS APPLICABLE AND NO LOOKBACK APPLIED
    [Documentation]    This test case has OPS applied with lookback=0 and tested for SONIA with startDate and endDate as Business Days.
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_006.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_006.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_006.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_006.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_006.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRSONIACA_007_WHEN START DATE IS WEEKDAY AND END DATE FALLS ON WEEKEND WITH LOOKBACK AND LOCKOUT
    [Documentation]    This test case has lookback > lockout applied and tested for SONIA with startDate as business day (Weekstart) and endDate as Weekend (Feb29th).
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_007.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_007.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_007.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_007.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_007.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRSONIACA_009_WHEN START DATE (TUES) AND END DATE (THURS) ARE BUSINESS DAYS AND OPS APPLIED WITH LOOKBACK APPLIED
    [Documentation]    This test case has OPS Applied tested for SONIA with startDate falling on Tuesday and endDate falling on Thursday
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_009.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_009.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_009.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_009.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_009.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRSONIACA_010_WHEN START DATE AND END DATE BOTH FALLS ON MONDAY AND OPS APPLIED WITH LOOKBACK APPLIED
    [Documentation]    This test case has OPS Applied tested for SONIA with startDate and endDate falling on Monday
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_010.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_010.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_010.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_010.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_010.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRSONIACA_016_WHEN START DATE AND END DATE BOTH FALLS ON MONDAY AND OPS APPLIED WITH LOOKBACK APPLIED AND DAY COUNT CONVENTION=ACT/360
    [Documentation]    This test case has OPS Applied tested for SONIA with startDate and endDate falling on Monday and dayCountConvention=ACT/360
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_016.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_016.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_016.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_016.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_016.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRSONIACA_019_WHEN START DATE AND END DATE BOTH FALLING ON WEEKENDS
    [Documentation]    This test case has lookback < lockout applied and tested for SONIA with startDate and endDate falling on weekend.
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_019.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_019.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_019.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_019.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_019.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRSONIACA_020_WHEN START DATE AND END DATE BOTH FALLING ON WEEKENDS AND ONLY LOCKOUT IS APPLIED
    [Documentation]    This test case has only lockout applied and tested for SONIA with startDate and endDate falling on weekend.
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_020.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_020.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_020.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_020.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_020.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRSONIACA_021_WHEN START DATE FALLS ON YEAR START (HOLIDAY) AND END DATE IS A WEEKDAY WITH LOOKBACK AND LOCKOUT IS APPLIED
    [Documentation]    This test case has lookback=lockout applied with startDate as Holiday(yearStart) and endDDate as a weekday.
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_021.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_021.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_021.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_021.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_021.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRSONIACA_023_WHEN START DATE FALLS ON WEEKEND (29thFeb) AND END DATE IS A LONG WEEKEND WITH LOOKBACK AND LOCKOUT IS APPLIED
    [Documentation]    This test case has lookback < lockout applied with startDate as weekend(Feb 29th) and endDDate falls on long weekend.
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_023.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_023.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_023.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_023.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_023.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRSONIACA_025_WHEN START DATE FALLS ON HOLIDAY AND END DATE IS WEEKDAY WITH LOOKBACK AND LOCKOUT APPLIED AND DAY COUNT CONVENTION=ACT/ACT (non-leap year)
    [Documentation]    This test case has lookback > lockout applied with startDate as Holiday and endDate falling on Weekday and dayCountConvention=ACT/ACT (Non-Leap year)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_025.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_025.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_025.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_025.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_025.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRSONIACA_028_WHEN START DATE AND END DATE FALLS ON TUESDAY WITH OPS APPLIED 
    [Documentation]    This test case has lookback / OPS applied with startDate and endDate falling on Tuesday 
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_028.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_028.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_028.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_028.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_028.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_VALIDATE RATE_FOR_TC_ARRSONIACA_029_WHEN START DATE FALLS ON WED AND END DATE ON TUESDAY WITH OPS APPLIED 
    [Documentation]    This test case has lookback > lockout applied with startDate ON Wednesday and endDate falling on Weekday
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\CARates_Requests\\SONIA\\Request_ARRSONIACA_029.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_029.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_029.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\CARates_Response\\SONIA\\Response_ARRSONIACA_029.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\CARates\\SONIA\\Response_ARRSONIACA_029.txt    ${IGNORED_KEYS_JSON_COMPARE}
