*** Settings ***
Library    RequestsLibrary  
Library    JsonLibrary    
Library    String    
# Library    GenerateOidcToken
Library    BaselineComparator    

# Library    Collections   
# Library    OperatingSystem 
Variables    ../../ConfigFile/GlobalConfig.py
Resource    ../../ConfigFile/ImportFile.robot



Suite Teardown    Delete All Sessions

Test Setup    GIVEN VALID AUTHENTICATION TOKEN AND SESSION IS CREATED

*** Variables ***
@{IGNORED_KEYS_JSON_COMPARE}    Create List    comment    legalDisclaimer    lastUpdatedFromSource

${HEADERS}
${RESPONSE}
${API_REQUEST_FROM_FILE}



*** Test Cases ***

GET_ARRCSOFRIND_001_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON FRIDAY AND END DATE FALLS ON SATURDAY
    [Documentation]    ARRCSOFRIND_001_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_001.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_001.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_001.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_001.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_001.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSOFRIND_002_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON FRIDAY AND END DATE FALLS ON MONDAY
    [Documentation]    ARRCSOFRIND_002_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_002.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_002.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_002.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_002.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_002.txt    ${IGNORED_KEYS_JSON_COMPARE}


GET_ARRCSOFRIND_003_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON FRIDAY AND END DATE FALLS ON SUNDAY
    [Documentation]    ARRCSOFRIND_003_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_003.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_003.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_003.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_003.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_003.txt    ${IGNORED_KEYS_JSON_COMPARE}
  
GET_ARRCSOFRIND_004_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON MONDAY AND END DATE FALLS ON SATURDAY
    [Documentation]    ARRCSOFRIND_004_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_004.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_004.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_004.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_004.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_004.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSOFRIND_005_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON MONDAY AND END DATE FALLS ON MONDAY
    [Documentation]    ARRCSOFRIND_005_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_005.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_005.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_005.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_005.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_005.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSOFRIND_006_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON MONDAY AND END DATE FALLS ON WEDNESDAY
    [Documentation]    ARRCSOFRIND_006_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_006.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_006.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_006.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_006.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_006.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSOFRIND_007_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON MONDAY AND END DATE FALLS ON MONDAY WITH DATE RANGE OF 1 WEEK
    [Documentation]    ARRCSOFRIND_007_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_007.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_007.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_007.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_007.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_007.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSOFRIND_008_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON MONDAY AND END DATE FALLS ON TUESDAY
    [Documentation]    ARRCSOFRIND_008_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_008.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_008.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_008.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_008.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_008.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSOFRIND_009_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON MONDAY AND END DATE FALLS ON SUNDAY
    [Documentation]    ARRCSOFRIND_009_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_009.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_009.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_009.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_009.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_009.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSOFRIND_010_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON MONDAY AND END DATE FALLS ON FRIDAY (HOLIDAY)
    [Documentation]    ARRCSOFRIND_010_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_010.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_010.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_010.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_010.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_010.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSOFRIND_011_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON WEDNESDAY AND END DATE FALLS ON FRIDAY
    [Documentation]    ARRCSOFRIND_011_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_011.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_011.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_011.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_011.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_011.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSOFRIND_012_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON THURSDAY AND END DATE FALLS ON SUNDAY
    [Documentation]    ARRCSOFRIND_012_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_012.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_012.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_012.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_012.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_012.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSOFRIND_013_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON TUESDAY AND END DATE FALLS ON SATURDAY
    [Documentation]    ARRCSOFRIND_013_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_013.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_013.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_013.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_013.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_013.txt    ${IGNORED_KEYS_JSON_COMPARE}
     
GET_ARRCSOFRIND_014_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON TUESDAY AND END DATE FALLS ON THURSDAY
    [Documentation]    ARRCSOFRIND_014_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_014.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_014.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_014.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_014.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_014.txt    ${IGNORED_KEYS_JSON_COMPARE}
     
GET_ARRCSOFRIND_015_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON TUESDAY AND END DATE FALLS ON MONDAY
    [Documentation]    ARRCSOFRIND_015_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_015.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_015.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_015.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_015.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_015.txt    ${IGNORED_KEYS_JSON_COMPARE}
     
GET_ARRCSOFRIND_016_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON TUESDAY AND END DATE FALLS ON FRIDAY
    [Documentation]    ARRCSOFRIND_016_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_016.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_016.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_016.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_016.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_016.txt    ${IGNORED_KEYS_JSON_COMPARE}
     
GET_ARRCSOFRIND_017_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON WEDNESDAY AND END DATE FALLS ON THURSDAY
    [Documentation]    ARRCSOFRIND_017_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_017.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_017.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_017.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_017.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_017.txt    ${IGNORED_KEYS_JSON_COMPARE}
     
GET_ARRCSOFRIND_018_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON THURSDAY AND END DATE FALLS ON FRIDAY
    [Documentation]    ARRCSOFRIND_018_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_018.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_018.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_018.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_018.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_018.txt    ${IGNORED_KEYS_JSON_COMPARE}
     
GET_ARRCSOFRIND_019_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON THURSDAY AND END DATE FALLS ON FRIDAY WITH DATE RANGE OF 1 DAY
    [Documentation]    ARRCSOFRIND_019_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_019.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_019.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_019.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_019.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_019.txt    ${IGNORED_KEYS_JSON_COMPARE}
     
GET_ARRCSOFRIND_020_VALIDATE AVERAGE RATE CALCULATED FROM INDEX_WHEN START DATE IS ON FRIDAY AND END DATE FALLS ON SUNDAY
    [Documentation]    ARRCSOFRIND_020_This test case reads GET request from a file and sends GET request, used for comparing average rates from Index
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Index_Requests\\Request_ARRCSOFRIND_020.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_020.txt
    

     THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
     AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_020.txt    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
     AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Index_Response\\Response_ARRCSOFRIND_020.txt    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Index\\Response_ARRCSOFRIND_020.txt    ${IGNORED_KEYS_JSON_COMPARE}