*** Settings ***
Library    RequestsLibrary  
Library    JsonLibrary    
Library    String    
# Library    GenerateOidcToken
Library    BaselineComparator    

# Library    Collections   
# Library    OperatingSystem 
Variables    ../../ConfigFile/GlobalConfig.py
Resource    ../../ConfigFile/ImportFile.robot



Suite Teardown    Delete All Sessions

Test Setup    GIVEN VALID AUTHENTICATION TOKEN AND SESSION IS CREATED

*** Variables ***
@{IGNORED_KEYS_JSON_COMPARE}    Create List    comment    legalDisclaimer    lastUpdatedFromSource

${HEADERS}
${RESPONSE}
${API_REQUEST_FROM_FILE}



*** Test Cases ***

GET_ARRCSONIATEN_001_VALIDATE AVERAGE COMPOUNDED RATE FOR TENOR = 30D AND VALUE_DATE = THURSDAY
    [Documentation]    This test case sends GET request for tenors and compares the response for Tenor=30D and valueDate falling on Thursday
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_001.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_001.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_001.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_001.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_001.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_002_VALIDATE AVERAGE COMPOUNDED RATE FOR TENOR = 30D AND VALUE_DATE = SUNDAY
    [Documentation]    This test case sends GET request for tenors and compares the response for Tenor=30D and valueDate falling on Sunday
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_002.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_002.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_002.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_002.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_002.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_003_VALIDATE AVERAGE COMPOUNDED RATE FOR TENOR = 30D AND VALUE_DATE = MONDAY
    [Documentation]    This test case sends GET request for tenors and compares the response for Tenor=30D and valueDate falling on Monday
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_003.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_003.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_003.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_003.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_003.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_004_VALIDATE AVERAGE COMPOUNDED RATE FOR TENOR = 30D AND VALUE_DATE = SUNDAY (LONG WEEKEND)
    [Documentation]    This test case sends GET request for tenors and compares the response for Tenor=30D and valueDate falling on Sunday (Long Weekend)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_004.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_004.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_004.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_004.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_004.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_005_VALIDATE AVERAGE COMPOUNDED RATE FOR TENOR = 180D AND VALUE_DATE = HOLIDAY (GOOD FRIDAY)
    [Documentation]    This test case sends GET request for tenors and compares the response for Tenor=180D and valueDate falling on Friday (Good friday: Holiday)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_005.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_005.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_005.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_005.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_005.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_006_VALIDATE AVERAGE COMPOUNDED RATE FOR TENOR = 180D AND VALUE_DATE = THURSDAY
    [Documentation]    This test case sends GET request for tenors and compares the response for Tenor=180D and valueDate falling on Thursday (Next day being public Holiday)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_006.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_006.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_006.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_006.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_006.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_007_VALIDATE AVERAGE COMPOUNDED RATE FOR ALL TENORS AND VALUE_DATE = SATURDAY
    [Documentation]    This test case sends GET request for tenors and compares the response for all Tenors and valueDate falling on Saturday
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_007.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_007.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_007.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_007.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_007.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_008_VALIDATE AVERAGE COMPOUNDED RATE FOR ALL TENORS AND VALUE_DATE = SUNDAY
    [Documentation]    This test case sends GET request for tenors and compares the response for all Tenors and valueDate falling on Sunday
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_008.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_008.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_008.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_008.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_008.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_009_VALIDATE AVERAGE COMPOUNDED RATE FOR ALL TENORS AND VALUE_DATE = FRIDAY
    [Documentation]    This test case sends GET request for tenors and compares the response for all Tenors and valueDate falling on FRIDAY
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_009.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_009.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_009.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_009.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_009.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_010_VALIDATE AVERAGE COMPOUNDED RATE FOR ALL TENORS AND VALUE_DATE = SATURDAY (LEAP YEAR : 29thFeb)
    [Documentation]    This test case sends GET request for tenors and compares the response for all Tenors and valueDate falling on SATURDAY (LEAP YEAR : 29thFeb)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_010.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_010.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_010.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_010.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_010.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_011_VALIDATE AVERAGE COMPOUNDED RATE FOR ALL TENORS AND VALUE_DATE = TUESDAY (END_OF_YEAR)
    [Documentation]    This test case sends GET request for tenors and compares the response for all Tenors and valueDate falling on TUESDAY (END_OF_YEAR)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_011.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_011.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_011.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_011.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_011.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_012_VALIDATE AVERAGE COMPOUNDED RATE FOR ALL TENORS AND VALUE_DATE = MONDAY
    [Documentation]    This test case sends GET request for tenors and compares the response for all Tenors and valueDate falling on MONDAY
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_012.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_012.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_012.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_012.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_012.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_013_VALIDATE AVERAGE COMPOUNDED RATE FOR ALL TENORS AND VALUE_DATE = MONDAY (START_OF_WEEK)
    [Documentation]    This test case sends GET request for tenors and compares the response for all Tenors and valueDate falling on MONDAY
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_013.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_013.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_013.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_013.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_013.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_014_VALIDATE AVERAGE COMPOUNDED RATE FOR ALL TENORS AND VALUE_DATE = SUNDAY 
    [Documentation]    This test case sends GET request for tenors and compares the response for all Tenors and valueDate falling on SUNDAY
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_014.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_014.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_014.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_014.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_014.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_015_VALIDATE AVERAGE COMPOUNDED RATE FOR TENOR = 7D AND VALUE_DATE = FRIDAY 
    [Documentation]    This test case sends GET request for tenor = 7D and compares the response for  and valueDate falling on FRIDAY
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_015.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_015.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_015.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_015.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_015.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_016_VALIDATE AVERAGE COMPOUNDED RATE FOR TENOR = 60D AND VALUE_DATE = TUESDAY
    [Documentation]    This test case sends GET request for tenor = 60D and compares the response for  and valueDate falling on TUESDAY
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_016.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_016.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_016.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_016.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_016.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_017_VALIDATE AVERAGE COMPOUNDED RATE FOR TENOR = 360D AND VALUE_DATE = MONDAY BEING HOLIDAY
    [Documentation]    This test case sends GET request for tenor = 360D and compares the response for  and valueDate falling on MONDAY which is a Holiday
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_017.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_017.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_017.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_017.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_017.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_018_VALIDATE AVERAGE COMPOUNDED RATE FOR TENOR = 90D AND VALUE_DATE = MONDAY
    [Documentation]    This test case sends GET request for tenor = 90D and compares the response for  and valueDate falling on MONDAY
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_018.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_018.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_018.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_018.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_018.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_019_VALIDATE AVERAGE COMPOUNDED RATE FOR TENOR = 180D AND VALUE_DATE = TUESDAY
    [Documentation]    This test case sends GET request for tenor = 180D and compares the response for  and valueDate falling on TUESDAY
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_019.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_019.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_019.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_019.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_019.txt    ${IGNORED_KEYS_JSON_COMPARE}

GET_ARRCSONIATEN_020_VALIDATE AVERAGE COMPOUNDED RATE FOR ALL TENORS AND VALUE_DATE = THURSDAY
    [Documentation]    This test case sends GET request for all tenors and compares the response for  and valueDate falling on TUESDAY(19-NOV-2019)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\SONIA\\Request_ARRCSONIATEN_020.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_020.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_020.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\SONIA\\Response_ARRCSONIATEN_020.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\SONIA\\Response_ARRCSONIATEN_020.txt    ${IGNORED_KEYS_JSON_COMPARE}
