*** Settings ***
Library    RequestsLibrary  
Library    JsonLibrary    
Library    String    
# Library    GenerateOidcToken
Library    BaselineComparator    

# Library    Collections   
# Library    OperatingSystem 
Variables    ../../ConfigFile/GlobalConfig.py
Resource    ../../ConfigFile/ImportFile.robot



Suite Teardown    Delete All Sessions

Test Setup    GIVEN VALID AUTHENTICATION TOKEN AND SESSION IS CREATED

*** Variables ***
@{IGNORED_KEYS_JSON_COMPARE}    Create List    comment    legalDisclaimer    lastUpdatedFromSource

${HEADERS}
${RESPONSE}
${API_REQUEST_FROM_FILE}



*** Test Cases ***

GET_LIQ116881_TC1_VALIDATE AVERAGE COMPOUNDED RATE FOR VALID TENORS AND VALUE_DATE = TUESDAY (Shows only 7D tenor)
    [Documentation]    This test case sends GET request for all valid tenors and compares the response for valueDate falling on TUESDAY (Shows only 7D tenor)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\LIQ-116881\\Request_LIQ116881_TC1.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC1.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC1.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC1.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC1.txt   ${IGNORED_KEYS_JSON_COMPARE}

GET_LIQ116881_TC2_VALIDATE AVERAGE COMPOUNDED RATE FOR VALID TENORS AND VALUE_DATE = MONDAY (Shows only 7D and 30D tenor)
    [Documentation]    This test case sends GET request for all valid tenors and compares the response for valueDate falling on MONDAY (Shows only 7D and 30D tenor)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\LIQ-116881\\Request_LIQ116881_TC2.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC2.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC2.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC2.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC2.txt   ${IGNORED_KEYS_JSON_COMPARE}

GET_LIQ116881_TC3_VALIDATE AVERAGE COMPOUNDED RATE FOR VALID TENORS AND VALUE_DATE = FRIDAY (Shows 7D,30D and 60D tenors)
    [Documentation]    This test case sends GET request for all valid tenors and compares the response for valueDate falling on FRIDAY (Shows 7D,30D and 60D tenor)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\LIQ-116881\\Request_LIQ116881_TC3.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC3.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC3.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC3.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC3.txt   ${IGNORED_KEYS_JSON_COMPARE}

GET_LIQ116881_TC4_VALIDATE AVERAGE COMPOUNDED RATE FOR VALID TENORS AND VALUE_DATE = SATURDAY (Shows 7D,30D and 60D tenors)
    [Documentation]    This test case sends GET request for all valid tenors and compares the response for valueDate falling on SATURDAY (Shows 7D,30D and 60D tenor)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\LIQ-116881\\Request_LIQ116881_TC4.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC4.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC4.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC4.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC4.txt   ${IGNORED_KEYS_JSON_COMPARE}

GET_LIQ116881_TC5_VALIDATE AVERAGE COMPOUNDED RATE FOR VALID TENORS AND VALUE_DATE = SUNDAY (Shows 7D,30D,60D and 90D tenors)
    [Documentation]    This test case sends GET request for all valid tenors and compares the response for valueDate falling on SUNDAY (Shows 7D,30D,60D and 90D tenors)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\LIQ-116881\\Request_LIQ116881_TC5.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC5.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC5.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC5.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC5.txt   ${IGNORED_KEYS_JSON_COMPARE}

GET_LIQ116881_TC6_VALIDATE AVERAGE COMPOUNDED RATE FOR VALID TENORS , RISK FREE RATE = SONIA AND VALUE_DATE = SATURDAY (Shows 7D,30D,60D and 90D tenors)
    [Documentation]    This test case sends GET request for all valid tenors and compares the response for valueDate falling on SATURDAY (Shows 7D,30D,60D and 90D tenors)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\LIQ-116881\\Request_LIQ116881_TC6.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC6.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC6.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC6.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC6.txt   ${IGNORED_KEYS_JSON_COMPARE}

GET_LIQ116881_TC7_VALIDATE AVERAGE COMPOUNDED RATE FOR ALL VALID TENORS , RISK FREE RATE = SONIA AND VALUE_DATE = TUESDAY (ALL tenors)
    [Documentation]    This test case sends GET request for all valid tenors and compares the response for valueDate falling on TUESDAY (ALL tenors)
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.1\\Tenor_Requests\\LIQ-116881\\Request_LIQ116881_TC7.txt    
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC7.txt
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC7.txt   ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.1\\Tenors_Response\\LIQ-116881\\Response_LIQ116881_TC7.txt   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.1\\Tenors\\LIQ-116881\\Response_LIQ116881_TC7.txt   ${IGNORED_KEYS_JSON_COMPARE}
