*** Settings ***
Library    RequestsLibrary  
Library    JsonLibrary    
Library    String    
# Library    GenerateOidcToken
Library    BaselineComparator    

# Library    Collections   
# Library    OperatingSystem 
Variables    ../../ConfigFile/GlobalConfig.py
Resource    ../../ConfigFile/ImportFile.robot



Suite Teardown    Delete All Sessions

Test Setup    GIVEN VALID AUTHENTICATION TOKEN AND SESSION IS CREATED

*** Variables ***
@{IGNORED_KEYS_JSON_COMPARE}    Create List    comment    legalDisclaimer    lastUpdatedFromSource

${HEADERS}
${RESPONSE}
${API_REQUEST_FROM_FILE}

*** Test Cases ***

TC001_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_001 WITH LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-04-10 endDate=2020-05-29 with lookback > lockout=0
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_001.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_001.json
    
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_001.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}
    
    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_001.json   ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_001.json    ${IGNORED_KEYS_JSON_COMPARE}

TC002_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_002 WITH LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-04-10 endDate=2020-05-29 with lookback > lockout=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_002.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_002.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_002.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_002.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_002.json    ${IGNORED_KEYS_JSON_COMPARE}

TC003_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_003 WITH LOCKOUT APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-05-02 endDate=2020-06-01 with lockout > lookback=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_003.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_003.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_003.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_003.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_003.json    ${IGNORED_KEYS_JSON_COMPARE}


TC004_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_004 WITH LOCKOUT APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-05-02 endDate=2020-06-01 with lockout > lookback=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_004.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_004.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_004.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_004.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_004.json    ${IGNORED_KEYS_JSON_COMPARE}

TC005_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_005 WITH LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-03-02 endDate=2020-05-29 with lookback > lockout=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_005.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_005.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_005.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_005.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_005.json    ${IGNORED_KEYS_JSON_COMPARE}

TC006_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_006 WITH LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-03-02 endDate=2020-05-29 with lookback > lockout=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_006.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_006.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_006.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_006.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_006.json    ${IGNORED_KEYS_JSON_COMPARE}

TC007_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_007 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-04-27 endDate=2020-05-30 with lookback < lockout
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_007.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_007.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_007.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_007.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_007.json    ${IGNORED_KEYS_JSON_COMPARE}

TC008_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_008 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-04-27 endDate=2020-05-30 with lookback < lockout
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_008.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_008.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_008.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_008.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_008.json    ${IGNORED_KEYS_JSON_COMPARE}

TC009_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_009 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-04-27 endDate=2020-05-30 with lookback < lockout
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_009.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_009.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_009.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_009.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_009.json    ${IGNORED_KEYS_JSON_COMPARE}

TC010_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_010 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-04-27 endDate=2020-05-30 with lockout < lookback
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_010.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_010.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_010.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_010.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_010.json    ${IGNORED_KEYS_JSON_COMPARE}

TC011_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_011 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-04-27 endDate=2020-05-30 with lockout > lookback
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_011.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_011.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_011.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_011.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_011.json    ${IGNORED_KEYS_JSON_COMPARE}


TC012_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_012 WITH LOCKOUT APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-01-01 endDate=2020-05-25 with lockout > lookback=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_012.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_012.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_012.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_012.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_012.json    ${IGNORED_KEYS_JSON_COMPARE}

TC013_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_013 WITH LOCKOUT APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-01-01 endDate=2020-05-25 with lockout > lookback=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_013.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_013.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_013.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_013.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_013.json    ${IGNORED_KEYS_JSON_COMPARE}

TC014_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_014 WITH LOCKOUT APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-01-01 endDate=2020-05-26 with lockout > lookback=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_014.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_014.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_014.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_014.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_014.json    ${IGNORED_KEYS_JSON_COMPARE}

TC015_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_015 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-02-01 endDate=2020-05-31 with lookback > lockout
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_015.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_015.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_015.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_015.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_015.json    ${IGNORED_KEYS_JSON_COMPARE}


TC016_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_016 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-02-01 endDate=2020-05-31 with lookback > lockout
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_016.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_016.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_016.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_016.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_016.json    ${IGNORED_KEYS_JSON_COMPARE}


TC017_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_017 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-02-01 endDate=2020-05-31 with lookback > lockout
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_017.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_017.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_017.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_017.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_017.json    ${IGNORED_KEYS_JSON_COMPARE}


TC018_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_018 WITH LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-05-01 endDate=2020-06-01 with lookback > lockout=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_018.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_018.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_018.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_018.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_018.json    ${IGNORED_KEYS_JSON_COMPARE}


TC019_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_019 WITH LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-05-01 endDate=2020-06-01 with lookback > lockout=0
 
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_019.txt
    
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_019.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_019.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_019.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_019.json    ${IGNORED_KEYS_JSON_COMPARE}


TC020_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_020 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-03-01 endDate=2020-05-30 with lockout > lookback
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_020.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_020.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_020.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_020.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_020.json    ${IGNORED_KEYS_JSON_COMPARE}

TC021_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_021 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-03-01 endDate=2020-05-30 with lookback > lockout
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_021.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_021.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_021.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_021.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_021.json    ${IGNORED_KEYS_JSON_COMPARE}

TC022_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_022 WITH LOCKOUT APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-02-29 endDate=2020-05-24 with lockout > lookback=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_022.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_022.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_022.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_022.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_022.json    ${IGNORED_KEYS_JSON_COMPARE}

TC023_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_023 WITH LOCKOUT APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-02-29 endDate=2020-05-24 with lockout > lookback=0
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_023.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_023.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
    ${data}    Get File    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_023.json    encoding=utf-8-sig

    ${res}    Mx Compare Json With Baseline File     ${API_ACTUAL_RESPONSE_PATH}\\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_023.json    ${data}    ignored_keys=@{IGNORED_KEYS_JSON_COMPARE}

TC024_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_024 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-05-08 endDate=2020-06-06 with lookback = lockout
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_024.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_024.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_024.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_024.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_024.json    ${IGNORED_KEYS_JSON_COMPARE}

TC025_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_025 WITH LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-04-30 endDate=2020-05-31 with lookback > lockout=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_025.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_025.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_025.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_025.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_025.json    ${IGNORED_KEYS_JSON_COMPARE}

TC026_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_026 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-01-01 endDate=2020-05-29 with lookback > lockout
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_026.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_026.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_026.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_026.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_026.json    ${IGNORED_KEYS_JSON_COMPARE}

TC027_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_027 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-05-01 endDate=2020-06-30 with lookback < lockout
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_027.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_027.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_027.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_027.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_027.json    ${IGNORED_KEYS_JSON_COMPARE}

TC028_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_028 WITHOUT LOCKOUT AND LOOKBACK
    [Documentation]    This testcase covers scenario where startDate=2020-04-30 endDate=2020-05-29 with lookback=lockout=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_028.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_028.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    400
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_028.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_028.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_028.json    ${IGNORED_KEYS_JSON_COMPARE}


TC029_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_029 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-02-03 endDate=2020-02-29 with lookback < lockout
    
    GIVEN USER STORES API REQUEST FROM FILE   ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_029.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}    
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_029.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    
    ${data}    Get File    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_029.json    encoding=utf-8-sig

    ${res}    Mx Compare Json With Baseline File     ${API_ACTUAL_RESPONSE_PATH}\\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_029.json    ${data}    ignored_keys=@{IGNORED_KEYS_JSON_COMPARE}

TC030_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_030 WITH LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-04-28 endDate=2020-05-07 with lookback > lockout=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_030.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_030.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_030.json    ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_030.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_030.json    ${IGNORED_KEYS_JSON_COMPARE}

TC031_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_031 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-01-01 endDate=2020-05-30 with lookback > lockout
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_031.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_031.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    400
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_031.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_031.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\API_ARRCE2ECA_031.json    ${IGNORED_KEYS_JSON_COMPARE}

TC032_GET_VALIDATE AVERAGE RATES_FOR_ARRCE2ECA_032 WITH LOCKOUT AND LOOKBACK APPLIED
    [Documentation]    This testcase covers scenario where startDate=2020-05-01 endDate=2020-06-01 with lookback > lockout=0
    
    GIVEN USER STORES API REQUEST FROM FILE    ${INPUT_REQUEST_PATH}\\ARRCv1.3\\AverageRatesv1.3_Requests\\Request_ARRCE2ECA_032.txt
   
    WHEN USER SENDS A "GET" REQUEST    ${API_REQUEST_FROM_FILE}
    AND SAVES THE API RESPONSE    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_032.json
    THEN VERIFY RESPONSE STATUS   ${RESPONSE.status_code}    200
    AND VERIFY ACTUAL RESPONSE MATCHES WITH EXPECTED RESPONSE FILE    ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_032.json  ${RESPONSE.content}    ${IGNORED_KEYS_JSON_COMPARE}

    AND VERIFY ACTUAL RESPONSE FILE MATCHES WITH EXPECTED RESPONSE FILE     ${API_EXPECTED_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_032.json    ${API_ACTUAL_RESPONSE_PATH}\\ARRCv1.3\\AverageRatesv1.3_Response\\Response_ARRCE2ECA_032.json    ${IGNORED_KEYS_JSON_COMPARE}

